from datetime import datetime


class HtmlReporter:

    def generate(
        self,
        file_violations,
        function_violations,
        architecture_violations,
        circular_violations,
        source_analysis,
        score
    ):

        if score >= 90:
            score_color = "#28a745"
            status = "🟢 Excellent"
        elif score >= 70:
            score_color = "#ffc107"
            status = "🟡 Good"
        else:
            score_color = "#dc3545"
            status = "🔴 Needs Improvement"

        total_files = len(source_analysis)

        total_classes = sum(
            len(item["classes"])
            for item in source_analysis
        )

        total_functions = sum(
            len(item["functions"])
            for item in source_analysis
        )

        total_imports = sum(
            len(item["imports"])
            for item in source_analysis
        )

        html = f"""<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>CodeGuardian Report</title>

<link rel="stylesheet" href="reports/style.css">

</head>

<body>

<div class="container">

<h1>CodeGuardian Report</h1>

<p>

<b>Generated:</b>

{datetime.now().strftime("%d %B %Y %H:%M")}

</p>

<div class="dashboard">

<div
class="score"
style="color:{score_color};">

Architecture Score

</div>

<div class="progress">

<div
class="progress-bar"
style="width:{score}%; background:{score_color};">

</div>

</div>

<h2>{score}/100</h2>

<p class="status">

{status}

</p>

<div class="grid">

<div class="card blue">
<h3>📄 Files</h3>
<p>{total_files}</p>
</div>

<div class="card green">
<h3>🏛 Classes</h3>
<p>{total_classes}</p>
</div>

<div class="card green">
<h3>⚙ Functions</h3>
<p>{total_functions}</p>
</div>

<div class="card blue">
<h3>📦 Imports</h3>
<p>{total_imports}</p>
</div>

<div class="card orange">
<h3>⚠ Oversized Files</h3>
<p>{len(file_violations)}</p>
</div>

<div class="card orange">
<h3>⚠ Oversized Functions</h3>
<p>{len(function_violations)}</p>
</div>

<div class="card red">
<h3>❌ Architecture Issues</h3>
<p>{len(architecture_violations)}</p>
</div>

<div class="card red">
<h3>🔁 Circular Dependencies</h3>
<p>{len(circular_violations)}</p>
</div>

</div>

</div>
"""
        def section(
            title,
            headers,
            rows
        ):

            nonlocal html

            html += f"<h2>{title}</h2>"

            if not rows:

                html += """
<p class="ok">
✔ No issues found.
</p>
"""
                return

            html += "<table>"

            html += "<tr>"

            for header in headers:

                html += f"<th>{header}</th>"

            html += "</tr>"

            for row in rows:

                html += "<tr>"

                for cell in row:

                    html += f"<td>{cell}</td>"

                html += "</tr>"

            html += "</table>"
        section(
            "Oversized Files",
            ["File", "Lines"],
            [
                [
                    violation.file_path,
                    violation.line_count
                ]
                for violation in file_violations
            ]
        )

        section(
            "Oversized Functions",
            ["Function", "Lines"],
            [
                [
                    violation.function_name,
                    violation.line_count
                ]
                for violation in function_violations
            ]
        )

        section(
            "Architecture Violations",
            ["File", "Rule Broken"],
            [
                [
                    violation.source_file,
                    f"{violation.source_layer} → {violation.target_layer}"
                ]
                for violation in architecture_violations
            ]
        )

        section(
            "Circular Dependencies",
            ["Dependency Cycle"],
            [
                [
                    " → ".join(
                        violation.cycle
                    )
                ]
                for violation in circular_violations
            ]
        )

        html += """
<h2>Source Code Analysis</h2>

<table>

<tr>

<th>File</th>

<th>Classes</th>

<th>Functions</th>

<th>Imports</th>

</tr>
"""

        for item in source_analysis:

            html += f"""
<tr>

<td>{item["file"]}</td>

<td>{len(item["classes"])}</td>

<td>{len(item["functions"])}</td>

<td>{len(item["imports"])}</td>

</tr>
"""

        html += """
</table>

<div class="footer">

Generated by <b>CodeGuardian</b><br>

Version 1.0

</div>

</div>

</body>

</html>
"""

        with open(
            "report.html",
            "w",
            encoding="utf-8"
        ) as file:

            file.write(html)